# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicdetailmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='topiclistmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
