# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 10:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0002_auto_20170418_0940'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TopicDetailModel',
            new_name='TopicCommentModel',
        ),
        migrations.RenameModel(
            old_name='TopicListModel',
            new_name='TopicModel',
        ),
        migrations.AlterModelTable(
            name='topiccommentmodel',
            table='topic_comments',
        ),
        migrations.AlterModelTable(
            name='topicmodel',
            table='topics',
        ),
    ]
