# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopicDetailModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField()),
            ],
            options={
                'db_table': 'topic_detail',
                'ordering': ('created_time',),
            },
        ),
        migrations.CreateModel(
            name='TopicListModel',
            fields=[
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('content', models.TextField()),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'topic_list',
                'ordering': ('-updated_time',),
            },
        ),
        migrations.CreateModel(
            name='TopicNodeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('node_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'topic_node',
                'ordering': ('created_time',),
            },
        ),
        migrations.AddField(
            model_name='topiclistmodel',
            name='node_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='topic.TopicNodeModel'),
        ),
        migrations.AddField(
            model_name='topicdetailmodel',
            name='topic_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topic.TopicListModel'),
        ),
    ]
