# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 06:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TopicDetail',
            new_name='TopicDetailModel',
        ),
        migrations.RenameModel(
            old_name='TopicList',
            new_name='TopicListModel',
        ),
        migrations.RenameModel(
            old_name='TopicNode',
            new_name='TopicNodeModel',
        ),
    ]
